// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6oFlMcosb3lcyrxGv7EWh4NVfH-1dlPA',
    appId: '1:86046524555:web:f3a2e414718eaa6429c08e',
    messagingSenderId: '86046524555',
    projectId: 'components5b',
    authDomain: 'components5b.firebaseapp.com',
    storageBucket: 'components5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIVxR6WcVcnB048Dpy1XqVMkLv0YVfcvI',
    appId: '1:86046524555:android:8432db14f55d75f629c08e',
    messagingSenderId: '86046524555',
    projectId: 'components5b',
    storageBucket: 'components5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0oMN8RviR6w5I1Uy2mfWrqiVGf2Gmbxg',
    appId: '1:86046524555:ios:90f16322c90beb1329c08e',
    messagingSenderId: '86046524555',
    projectId: 'components5b',
    storageBucket: 'components5b.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
